# Generated by Django 3.2.18 on 2026-09-28 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webGym', '0004_banner_banner_button_main_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abo_type', models.CharField(choices=[('visits', 'По числу посещений'), ('month', 'Безлимит на месяц'), ('year', 'Безлимит на год')], default='month', max_length=10, verbose_name='Тип абонемента')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Начало действия')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Конец действия')),
                ('max_visits', models.PositiveIntegerField(default=0, help_text='Для типа «по числу посещений»', verbose_name='Лимит посещений')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abonements', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Абонемент',
                'verbose_name_plural': 'Абонементы',
                'permissions': [('can_manage_gate', 'Может работать на проходной'), ('can_manage_trainers', 'Может управлять тренерами')],
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entered_at', models.DateTimeField(auto_now_add=True, verbose_name='Время входа')),
                ('abonement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='webGym.abonement', verbose_name='Абонемент')),
                ('operator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_visits', to=settings.AUTH_USER_MODEL, verbose_name='Оператор проходной')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Посещение',
                'verbose_name_plural': 'Посещения',
                'ordering': ['-entered_at'],
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Телефон')),
                ('specialization', models.CharField(blank=True, max_length=120, null=True, verbose_name='Специализация')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='Стаж (лет)')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Тренер',
                'verbose_name_plural': 'Тренеры',
            },
        ),
    ]
