# Generated by Django 3.2.18 on 2026-09-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webGym', '0006_roles_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonement',
            name='card_code',
            field=models.CharField(blank=True, db_index=True, help_text='10 цифр. Если оставить пустым — сгенерируется автоматически.', max_length=10, null=True, unique=True, verbose_name='Код карты'),
        ),
    ]
